### ISSUE TITLE
disallowed to seed

### ISSUE THREAD

**Issue by theB264** [test-unit/test-unit#101]
```
invalid option: --seed=1234
Test::Unit automatic runner.
```
Why not?  Documentation I've found says this is okay.

`rake test TESTOPTS="--order=random --seed=1234"`

```
Rake::TestTask.new do |t, args|
  t.libs << "test"
  t.libs << "."
  t.test_files = FileList['test/test*.rb', 'test/dir_one/test*.rb']
  t.verbose = true
  t.warning = true
end
```

`ruby-1.9.3-p551`

**Comment by kou** [comment]
Documentation you've found is not for test-unit gem.
It's for `test/unit` bundled in Ruby 1.9, 2.0 and 2.1. The `test/unit` is a wrapper of minitest gem.

If you want to use `--seed`, uninstall test-unit gem.

**Comment by theB264** [comment]
Thank you.  Is there any way to run `test-unit` deterministically [using rake] if calls to `Kernel#rand` are made in the code being tested?  I'm looking for a solution that works for Ruby 1.9 - 2.2+

**Comment by kou** [comment]
> Is there any way to run test-unit deterministically [using rake] if calls to Kernel#rand are made in the code being tested?

Call `Kernel.#srand` by yourself.
