### ISSUE TITLE
sub_test_case 内のテストケースが、外側の同名のテストケースで隠される

### ISSUE THREAD

**Issue by wanabe** [test-unit/test-unit#104]
こんにちは。

sub_test_case を使っていると、テストケースがうまく実行されないケースがありましたので報告します。

```
require 'test/unit'

class MyTest < Test::Unit::TestCase
  test "foo" do
    p :outer
  end

  sub_test_case "inner" do
    test "foo" do
      p :inner
    end
  end
end
```

このとき inner::foo が実行されず、そのため :inner が印字されません。
inner::foo が実行されることを期待したのですが、どうでしょうか。
test-unit のバージョンは 3.0.8 および 3.0.9 で確認しました。

**Comment by kou** [comment]
その通りなので直して3.1.0をリリースしておきました！

**Comment by wanabe** [comment]
3.1.0 で期待していた動作になっていることを確認しました。
ありがとうございました。
