### ISSUE TITLE
--location で sub_test_case 内のテストを指定すると、外側のテストも実行される

### ISSUE THREAD

**Issue by wanabe** [test-unit/test-unit#105]
こんにちは。

--location を指定すると、想定していないテストが実行される場合がありましたので報告します。

```
require 'test/unit'

class MyTest < Test::Unit::TestCase
  test "foo" do
    p :should_not_be_printed
  end

  sub_test_case "inner" do
    test "bar" do
      # line 10
      p :should_be_printed
    end
  end
  # line 14
end
```

このようなテストケースで --location=10 ないし --location=14 とすると、定義したテストが両方実行され
:should_not_be_printed と :should_be_printed の両方が印字されます。
14 を指定した場合の挙動は不定でいいとは思うのですが、10 を指定した時は inner:bar だけが実行されてほしいです。

**Comment by wanabe** [comment]
Test::Unit::TestCase.test_defined? で、
```
            available_location = available_locations.reverse.find do |location|
              query_line >= location[:line]
            end
```
としている箇所が関係ありそうです。

**Comment by kou** [comment]
直して3.1.1をリリースました！
ただ、テストの数が多くなると遅くなりそうな実装なので、問題が出てきたら高速化が必要だと思っています。。。

**Comment by wanabe** [comment]
3.1.1 で期待通りの動作になっていることを確認しました。ありがとうございました。
速度も、手元で試した限りでは気がつかない程度でした。
