### ISSUE TITLE
Add assert_casecmp assertion

### ISSUE THREAD

**Issue by djberg96** [test-unit/test-unit#106]
There are times when I need to compare strings, but I don't know in advance if I'm going to get upper or lower case text back from certain methods, such as Win32 functions I've wrapped via FFI.

I would like to see an "assert_casecmp" assertion that would be used for comparing strings, but would ignore case differences. So, assert_casecmp('hello', 'hELlo') would pass.

While I realize I could manually downcase everything in my tests, that can be a bit of a pain, and sometimes I don't think of it until my CI platform informs me so.

**Comment by djberg96** [comment]
As a followup, it was pointed out that such an assertion would need to use a regex rather than downcase or casecmp to deal with non-ascii characters.

    'Á'.downcase == 'á' # => false
    'Á'.casecmp('á') # => -1
    %r(\A#{Regexp.escape('Á')}\z)i =~ 'á' # => 0

**Comment by djberg96** [comment]
Initial attempt:

    module Test::Unit::Assertions
      # Compare two strings, ignoring case.
      def assert_casecmp(str1, str2, message = nil)
        message = build_message(message, "#{str1} and #{str2} are not equivalent", object)
        assert_block(message) do
          (/\A#{Regexp.escape(arg1)}\z/i =~ arg2) == 0
        end
      end
    end

**Comment by kou** [comment]
Uhm...

`assert_casecmp` isn't generic to bundle test-unit. What about creating `test-unit-assert-casecmp` gem?

I think that the followings are better for reading (even they are bit of a pain for writing):

```ruby
assert_equal("hello", "hELlo".downcase)

def ignore_case_pattern(string)
  /\A#{Regexp.escape(string)}\z/i
end
assert_match(ignore_case_pattern("hello") ,
             "hELlo")
```
