### ISSUE TITLE
specify ruby version in gemspec

### ISSUE THREAD

**Issue by ipmsteven** [test-unit/test-unit#116]
seems that the last ruby 1.8.x test set up is removed in this commit(https://github.com/test-unit/test-unit/commit/7f5c44a6a08b026efc7e05187c1fa565407d82e8) which means `test-unit` is not supposed to be used under ruby 1.8, could we also add that in gemspec to stop people installing `test-unit` from 1.8 environment?

**Comment by kou** [comment]
Ruby 1.8 isn't unmaintained.
Should we care about unmaintained Ruby versions?

**Comment by ipmsteven** [comment]
yes, I mean could we do `s.required_ruby_version = Gem::Requirement.new(">= 1.9")` in the `gemspec` since it's unmaintained?

**Comment by kou** [comment]
Could you describe why should we add the code to `gemspec`?

Who does use unmaintained Ruby?

**Comment by magneland** [comment]
I also think the `gemspec` should be more accurate.
If someone wants to use Ruby 1.8.7 or earlier, maybe they can do it by forking the repo and rebuilding the gem themselves?

**Comment by kou** [comment]
> If someone wants to use Ruby 1.8.7 or earlier, maybe they can do it by forking the repo and rebuilding the gem themselves?

I think that he/she uses old released version such as 1.2.3.

Ruby 1.8 bundles test-unit. Normally, he/she doesn't need to install test-unit as gem.

**Comment by kou** [comment]
> If someone wants to use Ruby 1.8.7 or earlier,

BTW, why does he/she want to use Ruby 1.8.7 or earlier?

**Comment by jrgarcia** [comment]
I'm supporting Ruby 1.8.7 because Ruby 1.8.7-p374 is the latest package available in CentOS 6. It's old and ridiculous to support, but my project would have failed trying to install `test-unit` during `bundle install` instead of having to look for this. That's the whole purpose of [this attribute](http://guides.rubygems.org/specification-reference/#required_ruby_version=) in the specification.

**Comment by kou** [comment]
We never care about unsupported Ruby because we don't want to pay maintenance cost for unsupported Ruby.
If users use unsupported Ruby, they should use test-unit at your own risk. (For example, specifying test-unit version in `Gemfile`.)
