### ISSUE TITLE
No tests executed if `data()` specified and argument not specified

### ISSUE THREAD

**Issue by tagomoris** [test-unit/test-unit#122]
When I wrote a code like below, I expect it fails always (NoMethodError for missing `param`, or assertion failure if `param` is in arguments correctly).
But it executes no tests and successes against my expectation.

```ruby
require 'test-unit'

class DataTest < Test::Unit::TestCase
  data("param1" => 1, "param2" => 2)
  def test_mytest
    assert param.is_a? Numeric
    assert false, "this test always fails"
  end

  data("param1" => 1, "param2" => 2)
  test 'mytest' do
    assert param.is_a? Numeric
    assert false, "this test always fails"
  end
end
```

My expectation is:
* Test code (method) is executed, and fails with NoMethodError for `param`.

```
$ bundle exec ruby test/test_data.rb 
$ echo $?
0
```

Is it a bug or intentional?

**Comment by kou** [comment]
It's an expected behavior.
But it may confuse users who miss a parameter in their test method.

I added a feature that notifies the case and released a new version.
