### ISSUE TITLE
Why Collector::ObjectSpace is deprecated?

### ISSUE THREAD

**Issue by nalabjp** [test-unit/test-unit#125]
Hi,

I'm sorry to ask at the issue because I could not find the evidence.

Why Collector::ObjectSpace is deprecated?
https://github.com/test-unit/test-unit/blob/3.2.1/doc/text/news.md#200--2008-06-18
https://github.com/test-unit/test-unit/commit/2cf4df5dfc13ba3925172cc13510c61786d32847

Could you please tell me what's wrong Collector::ObjectSpace?
I want to use the collector to collect the test suite to flat as Collector::ObjectSpace, in order to run some tests in parallel with test-queue.gem.

Do you have any idea?

**Comment by kou** [comment]
Could you describe why `Collect::ObjectSpace` can work but `Collector::Descendant` can work?

**Comment by kou** [comment]
Or could you provide scripts that reproduce your problem?

**Comment by nalabjp** [comment]
Thank you for your response.

In my private project, it work both Collector::ObjectSpace also Collector::Descendant with `rake test`.

In the case that use Collector::ObjectSpace, I use monkey patch below.
https://github.com/test-unit/test-unit/blob/3.2.1/lib/test/unit/autorunner.rb#L476
```
def default_collector
  self.class.collector(:object_space)
end
```

The number of the suite, the number of the assertion and the test result is all the same in either case, it seems to me that there is no problem.

I use test-queue.gem with Rails in my private project.

The runner of test-unit in test-queue is using Collector::Descendant.
https://github.com/tmm1/test-queue/blob/v0.2.13/lib/test_queue/runner/testunit.rb#L35

In this case, the result of test-queue is below.
```
==> Summary (8 workers in 137.5750s)

    [ 8] 0 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         0 suites in 56.9413s      (pid 11868 exit 0)
    [ 5] 0 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         0 suites in 57.0850s      (pid 11865 exit 0)
    [ 1] 0 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         0 suites in 57.1874s      (pid 11861 exit 0)
    [ 7] 0 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         0 suites in 57.3002s      (pid 11867 exit 0)
    [ 2] 0 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         0 suites in 57.3057s      (pid 11862 exit 0)
    [ 4] 0 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         0 suites in 57.3074s      (pid 11864 exit 0)
    [ 6] 0 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         0 suites in 57.3167s      (pid 11866 exit 0)
    [ 3] 35 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         1 suites in 134.3096s      (pid 11863 exit 0)
```

As you see, this is not be processed in parallel.
The number of `@suite.tests` is only one in https://github.com/tmm1/test-queue/blob/v0.2.13/lib/test_queue/runner/testunit.rb#L36


However, in the case that uses Collector::ObjectSpace, it will be processed in parallel.

```
# moneky patch
require 'test/unit/collector/objectspace'
module TestQueue
  class Runner
    class TestUnit
      def initialize
        @suite = Test::Unit::Collector::ObjectSpace.new.collect
        tests = @suite.tests.sort_by{ |s| -(stats[s.to_s] || 0) }
        super(tests)
      end
    end
  end
end
```

```
==> Summary (8 workers in 95.5825s)

    [ 4] 6 tests, 9 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         4 suites in 82.5186s      (pid 60442 exit 0)
    [ 5] 7 tests, 14 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         4 suites in 82.8336s      (pid 60443 exit 0)
    [ 7] 6 tests, 10 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         5 suites in 83.4956s      (pid 60445 exit 0)
    [ 1] 2 tests, 5 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         2 suites in 86.6194s      (pid 60439 exit 0)
    [ 6] 2 tests, 3 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         2 suites in 87.6341s      (pid 60444 exit 0)
    [ 2] 3 tests, 7 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         1 suites in 90.5326s      (pid 60440 exit 0)
    [ 3] 5 tests, 6 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         3 suites in 91.8206s      (pid 60441 exit 0)
    [ 8] 4 tests, 16 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications         1 suites in 92.8622s      (pid 60446 exit 0)
```

In this case, The number of `@suite.tests` are 22.

I think, in the case that uses Collector::Descendant, the reason is that `root_test_cases` is only Test::Unit::TestCase of the parent class of ActiveSupport::TestCase in https://github.com/test-unit/test-unit/blob/3.2.1/lib/test/unit/collector.rb#L36

So, if there is a problem with the Collector::ObjectSpace, I would like to solve it.
But, I did not know why it is not recommended, and I was asked.

**Comment by kou** [comment]
Thanks for describing about it.
Could you provide a script (Rails project) that reproduces the problem? I want to try it on my environment.

**Comment by kou** [comment]
`Collector::ObjectSpace` is deprecated because it didn't work on JRuby.

**Comment by nalabjp** [comment]
Thanks for your reply.

I made a small project to reproduce my problem.
https://github.com/nalabjp/test-unit-test-queue-example

Please see README.md .

**Comment by nalabjp** [comment]
I update my repo, and I resolve this problem in https://github.com/nalabjp/test-unit-test-queue-example/commit/fbc5ea19cd716c6d57d059ea9da7ff65c8215b9d .

> Collector::ObjectSpace is deprecated because it didn't work on JRuby.

Thank you for your information.

I will close this issue now.
Thanks.

**Comment by kou** [comment]
It doesn't solve the real problem.
I sent a pull request to tmm1/test-queue#53.

**Comment by nalabjp** [comment]
After that, I noticed the same problem.
Thank you for sending a pull request to test-queue. 😄
