### ISSUE TITLE
Tests do not start with Rails 5.0.2 or later

### ISSUE THREAD

**Issue by k5trismegistus** [test-unit/test-unit#140]
Tests do not start after I updated Rails to 5.0.2.

This issue happened with
- Ruby 2.4.1
- Rails 5.0.2 and 5.1.0rc1
- test-unit 3.2.3

To search for the cause, I have modified [lib/test/unit.rb:499](https://github.com/test-unit/test-unit/blob/master/lib/test/unit.rb#L499).

```
Module.new do
  at_exit do
    if $!.nil? and Test::Unit::AutoRunner.need_auto_run?
      exit Test::Unit::AutoRunner.run
    end
  end
end
```

to

```
Module.new do
  at_exit do
    puts $!
    if $!.nil? and Test::Unit::AutoRunner.need_auto_run?
      exit Test::Unit::AutoRunner.run
    end
  end
end
```

With Rails 5.0.1, `p $!` shows `nil`, but Rails 5.0.2 or later shows `#<SystemExit: exit>`.
So `$!.nil?` become `false` and `exit Test::Unit::AutoRunner.run` is not called.

Both trials use Ruby 2.4.1, and other gem which version changed is nio4r(1.2.1 -> 2.0.0)

**Comment by k5trismegistus** [comment]
```ruby
if $!.nil? || $!.class == SystemExit and Test::Unit::AutoRunner.need_auto_run?
```

With this if-statement, test runs.

**Comment by kou** [comment]
Could you show us a Rails application that reproduces this problem?

**Comment by kou** [comment]
I want to try it on my environment.

**Comment by k5trismegistus** [comment]
Sorry, it is not OSS project.
Thanks.

**Comment by kou** [comment]
I just want to reproduce this problem on my environment. So I don't need a real Rails application. It's OK that a sample Rails application that reproduces this problem.

**Comment by k5trismegistus** [comment]
I tried, but I couldn't manage to reproduce application...
It seems to be our application's problem.

Thank you for paying attention.

**Comment by kou** [comment]
OK. The following code may help you to solve this problem.

```ruby
Module.new do
  at_exit do
    puts $!
    puts $!.backtrace
    if $!.nil? and Test::Unit::AutoRunner.need_auto_run?
      exit Test::Unit::AutoRunner.run
    end
  end
end
```
