### ISSUE TITLE
Thread-unsafe use of hash for method_locations

### ISSUE THREAD

**Issue by headius** [test-unit/test-unit#159]
I ran into this due to a multithreaded method-definition test in JRuby: https://github.com/jruby/jruby/blob/556d339cee43726b747e981f6908ea6c520f413b/test/jruby/test_thread.rb#L181

The logic  here tests that multiple threads can be redefining the  same method concurrently without breaking anything in the JRuby runtime. However, because TestCase adds all newly defined methods to its `method_locations` hash, this test can trigger concurrency errors on implementations that don't guarantee thread-safety of Hash.

https://github.com/test-unit/test-unit/blob/master/lib/test/unit/testcase.rb#L153

There are multiple places that this hash is accessed, but at a minimum I believe the mutations should be synchronized as below:

testcase.rb:
```ruby
...
        private
        # @private
        @@method_locations = {}
        METHOD_LOCATIONS_MUTEX  = Mutex.new
        private_constant :METHOD_LOCATIONS_MUTEX
        # @private
        def method_locations
          METHOD_LOCATIONS_MUTEX.synchronize do
            @@method_locations[self] ||= []
          end
        end
```

Arguably this is a broken expectation in our test, since we are redefining methods on the actual test class, and I am modifying the test in JRuby. However others may also test concurrent definition of methods and make the same mistake, so I think synchronizing this collection is warranted.

**Comment by kou** [comment]
Thanks for your report.
I've fixed this.
