### ISSUE TITLE
"ArgumentError: invalid byte sequence in Windows-31J" raised on Japanese Windows

### ISSUE THREAD

**Issue by masa-kunikata** [test-unit/test-unit#161]
Hi
The error causes when test scirpt files have a special conditions below.

* defining test in a "block" (not a method)
* no magic comment on a test script file

I think it is related to the closed issue #87 .

Is it necessary to specify an encoding magic comment, when writing tests in blocks?

---

Sample tests and details
https://github.com/masa-kunikata/test_unit_gem_encoding_error

in Japanese
https://github.com/masa-kunikata/test_unit_gem_encoding_error/blob/master/README.jp.md

**Comment by masa-kunikata** [comment]
I could get it solved by setting the test script encoding to UTF-8 if it doesn't have the magic comment.

the commit
https://github.com/masa-kunikata/test-unit/commit/08f6b6c449a94d5eb8b5f86c108d702479aeac35

I think it is preferable because "The default script encoding is Encoding::UTF-8 after v2.0."

In the Ruby 1.9 environment, it should be strictly US-ASCII, but since UTF-8 is a compatible encoding it is not a problem.

**Comment by kou** [comment]
Thanks for your report.
I've fixed this.
