### ISSUE TITLE
user_message returns nil when user provides a message

### ISSUE THREAD

**Issue by xgraffm** [test-unit/test-unit#162]
ruby 2.5.1p57
test-unit 3.3.0

I am providing validation specific messages into the assertions and can see that as part of the message but can not retrieve just the message i provided via user_message.  It seemed this would be the intended purpose of the user_message method returning the head portion of the assertion error message.  In stepping through the code, the user provided message and the default error message are combined and delimited by "." but I'd rather access via e.user_message than assuming i can always e.message.split(".").first

assert_true(false, "GTM not found at first node after body")
rescue => e
(byebug) e.message
"GTM not found at first node after body.\n<true> expected but was\n<false>"
(byebug) e.user_message
nil 

Thanks.

**Comment by kou** [comment]
Thanks for your report.
I've implemented.
