### ISSUE TITLE
Command option to ignore specific test name in the specific test suite?

### ISSUE THREAD

**Issue by junaruga** [test-unit/test-unit#169]
Hello,

Seeing the source code of the options.
https://github.com/test-unit/test-unit/blob/master/lib/test/unit/autorunner.rb

There is the option to ignore the specific test suite: `--ignore-testcase=TESTCASE`.
There is the option to ignore the specific test name: `--ignore-name=NAME`.

Is there the option to ignore the specific suite's specific test name?
For example, I want to ignore only `TestCaseB`'s `test_a` in the following case.

* TestCaseA, test_a, test_b
* TestCaseB, test_a, test_b

Using `omit` method is recommended in this case?
https://stackoverflow.com/questions/2927405/how-to-skip-certain-tests-with-testunit

Thank you.

**Comment by junaruga** [comment]
This question is related to Ruby project's this issue.
https://bugs.ruby-lang.org/issues/16936

**Comment by kou** [comment]
You can use `--ignore-name=TestCaseB#test_a` with test-unit 3.3.6.

**Comment by junaruga** [comment]
Thank you for the answer.

**Comment by junaruga** [comment]
Reading the part of the option `--ignore-name`, does unit-test support `/PATTERN/` for the test case too? It's like `--ignore-name=/^TestCaseB#test_a$/`.

```
          o.on("--ignore-name=NAME", String,
               "Ignores tests matching NAME.",
               "Use '/PATTERN/' for NAME to use regular expression.",
               "Regular expression accepts options.",
               "Example: '/taRget/i' matches 'target' and 'TARGET'") do |name|
            name = prepare_name(name)
            @filters << lambda do |test|
              not match_test_name(test, name)
            end
          end
```

Though I might be wrong, it seems the following logic only considers the test case if the pattern is `String` class.

```
      def match_test_name(test, pattern)
        return true if pattern === test.method_name
        return true if pattern === test.local_name
        if pattern.is_a?(String)
          return true if pattern === "#{test.class}##{test.method_name}"
          return true if pattern === "#{test.class}##{test.local_name}"
        end
        false
      end
```

It seems minitest considers it, though I have not tested it yet.

https://github.com/seattlerb/minitest/blob/32d49db55d80b8479237898f07d161bb52ef905c/lib/minitest.rb#L309-L322

**Comment by junaruga** [comment]
Sorry. Maybe the current implementation in unit-test is right.

`filter === "#{self}##{m}"` in minitest matches only if the `filter` is String`.

```
      filtered_methods = self.runnable_methods.find_all { |m|
        filter === m || filter === "#{self}##{m}"
      }
```
