### ISSUE TITLE
test-unit tests should ignore <internal: backtrace entries

### ISSUE THREAD

**Issue by eregon** [test-unit/test-unit#171]
Specifically, https://github.com/test-unit/test-unit/blob/ea81cf9545368ca9fae704454fe67d81ad9fe2c9/test/test-test-case.rb#L65-L68 should also ignore `<internal:` backtrace entries.

`<internal:` is the standard way to mark internal sources, also used in CRuby 2.7+.

Additionally, when running the tests on TruffleRuby I noticed 
https://github.com/test-unit/test-unit/blob/ea81cf9545368ca9fae704454fe67d81ad9fe2c9/test/test-assertions.rb#L648
should be `RUBY_ENGINE == "jruby"` instead.

I would make a PR, but the license seems quite complicated here (it's not just the standard 2-clause BSDL/Ruby).

From https://github.com/oracle/truffleruby/issues/2059
cc @gogainda

**Comment by eregon** [comment]
@kou Thank you!

**Comment by kou** [comment]
Thanks for your report!

> the license seems quite complicated here (it's not just the standard 2-clause BSDL/Ruby).

The license still uses the old Ruby license (dual license of GPLv2+ and Ruby's) because we didn't try asking copyright holders to license change.

There are some exceptions (additional license). I added LGPLv2.1+ to files written by me:

  * lib/test/unit/diff.rb: triple license of old Ruby's (GPLv2+/Ruby's), the PSF license (because I ported Python's difflib implementation) and LGPLv2.1+
  * Rakefile and lib/test-unit.rb: dual license of old Ruby's (GPLv2+/Ruby's) and LGPLv2.1+.

**Comment by gogainda** [comment]
@kou looks like we can add truffle ruby to the CI pipeline

**Comment by kou** [comment]
Added: https://travis-ci.org/github/test-unit/test-unit/jobs/714613316

But it's failed because TruffleRuby doesn't provide `RbConfig::CONFIG["datadir"]`. We should not assume that TruffleRuby provides `RbConfig::CONFIG["datadir"]`?

**Comment by kou** [comment]
I've change the gettext gem to not assume `RbConfig::CONFIG["datadir"]` availability.

But there are some failures. We should use a new issue if we need to discuss TruffleRuby support.

**Comment by gogainda** [comment]
@kou I believe truffleruby-dev should be used for Travis CI since since "stable" version doesn't have all needed  changes

**Comment by eregon** [comment]
Yes, `truffleruby-head` (since TravisCI uses RVM) defines `RbConfig::CONFIG["datadir"]`.
But there are still 2 other issues as shown in https://travis-ci.org/github/test-unit/test-unit/jobs/714613316, the TruffleRuby team will try to take a look at those.

**Comment by eregon** [comment]
@gogainda I think it's better to make sure all tests pass (e.g., by running the CI on a fork) before asking to add to CI.
@kou Thank you for trying to add TruffleRuby in CI, I hope we can fix the remaining 2 failures soon (https://github.com/oracle/truffleruby/issues/2059#issuecomment-668268884). Feel free to mark it as `allow_failures` or remove it until we figure how to fix those 2 failures.

**Comment by kou** [comment]
OK.
I keep the current `.travis.ci` as is because TruffleRuby will fix them.
If test-unit should be changed like this case, please create a new issue or pull request.

**Comment by gogainda** [comment]
@eregon oh, sorry for that, I was pretty sure that all failing tests were fixed by the time, yet hadn't run the test suit. Will be more vigilant about it next time
@kou sorry of the inconvenience

**Comment by eregon** [comment]
@kou All test-unit tests pass locally for me now.
Can you switch to `truffleruby-head` in CI? Then all tests should pass.

**Comment by kou** [comment]
Thanks for notifying this!
I've added `truffleruby-head` instead of switching to `truffleruby-head`. It passed: https://travis-ci.org/github/test-unit/test-unit/jobs/715635504
I'll keep the `truffleruby` job to confirm the status with the released TruffleRuby continuously.
