### ISSUE TITLE
Which is license GPL or BSD?

### ISSUE THREAD

**Issue by wataash** [test-unit/test-unit#172]
Which is license GPL or BSD?

[README](https://github.com/test-unit/test-unit/blob/3.3.6/README.md) says:

> This software is distributed under the same terms as ruby.

and this argument has been exist since [2008](https://github.com/test-unit/test-unit/commit/c7b522d), so I guess it means Ruby license or GPL-2.0-only. But this combination has problems and changed to Ruby license + BSD-2-Clause in 2010.

- http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/31971
- https://github.com/ruby/ruby/commit/2cd6800fd

So in test/unit, which one below is intended?

- Ruby license or GPL-2.0-only
- Ruby license or BSD-2-Clause

**Comment by kou** [comment]
Ruby license or GPL-2.0-only

See also: https://github.com/test-unit/test-unit/issues/171#issuecomment-668213522

**Comment by wataash** [comment]
Thank you.
I wrote it at #173.
