### ISSUE TITLE
License migration from the old Ruby's to the new Ruby's

### ISSUE THREAD

**Issue by kou** [test-unit/test-unit#174]
We're using the old Ruby's (dual license of the original license for Ruby and GPLv2) because the test-unit authors listed in [COPYING](https://github.com/test-unit/test-unit/blob/master/COPYING) (@kou, @zenspider and @ntalbott) don't migrate our license.

If the test-unit authors accept, we can migrate our license from the old Ruby's to the new Ruby's by using the following clause like Ruby did: http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/31971

```text
  2. You may modify your copy of the software in any way, provided that
     you do at least ONE of the following:
       d) make other distribution arrangements with the author.
```

I accept the migration. @zenspider @ntalbott Do you accept the migration?

**Comment by ntalbott** [comment]
I'm fine with it. :+1:

**Comment by kou** [comment]
Thanks!

**Comment by zenspider** [comment]
I'm not sure I ever put any changes into it... but I'm fine with it as well. Sorry for the delay.

**Comment by kou** [comment]
Thanks!

**Comment by kou** [comment]
Done.
