### ISSUE TITLE
History of 'compatibility layer' with minitest

### ISSUE THREAD

**Issue by andyw8** [test-unit/test-unit#217]
Hi @kou

I wanted to follow-up from https://github.com/test-unit/test-unit/pull/214 to better understand test-unit's history and how it relates to Minitest. I'm planning to publish a blog post about this.

I understand that the test-unit that shipped with Ruby 1.9.3 was just a 'compatibility layer' on top of Minitest:

https://github.com/seattlerb/minitest/issues/82#issuecomment-3387948

But on the current Ruby (3.1.1) this appears to no longer the case, as there is no mention of Minitest in `Test::Unit::TestCase.ancestors`.

Does this mean that test-unit was removed, and then subsequently re-added to Ruby? I've been looking at the Ruby changelogs to try determine if and when that happened, but I haven't be able to find an answer so far. (Also unfortunately it's difficult to run older Ruby versions on a newer OS).

**Comment by kou** [comment]
> I understand that the test-unit that shipped with Ruby 1.9.3 was just a 'compatibility layer' on top of Minitest:

This is not correct.

See https://www.clear-code.com/blog/2014/11/6.html in Japanese (English translation by Google Translation: https://www-clear--code-com.translate.goog/blog/2014/11/6.html?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja&_x_tr_pto=wapp ) and https://slide.rabbit-shocker.org/authors/kou/rubykaigi-2015/ .

**Comment by andyw8** [comment]
Oh, very interesting article, thanks for sharing!

**Comment by kou** [comment]
Can we close this?
