### ISSUE TITLE
assert_output support

### ISSUE THREAD

**Issue by akostadinov** [test-unit/test-unit#227]
Hello, can `assert_output` be implemented? Like in minitest?

**Comment by kou** [comment]
Could you explain your use case?

FYI: We have `capture_output`:

```ruby
stdout, stderr = capture_output do
  # ...
end
assert_equal(["expected stdout", "expected stderr"],
             [stdout, stderr])
```

**Comment by akostadinov** [comment]
hmm, I didn't notice that. I looked for `capture_io`. But the above works, thank you!

**Comment by akostadinov** [comment]
I don't know if it can be made more easily discoverable. I literally switched to minitest for this. Now I'm back to test-unit .

**Comment by kou** [comment]
We may want to create a test-unit <-> minitest API mapping cheat seat.
If you want to work on it, feel free to open a pull request.

**Comment by akostadinov** [comment]
Maybe not really needed. Hopefully any other lost soul looking for `capture_io` will search and find this issue to know `capture_output` exists. Everything else is mostly the same or easily discoverable. Moreover ActiveSupport already implements the `setup/teardown/test` class methods so these should be familiar to most people.

Thank you again for the quick reply!
