### ISSUE TITLE
Show N slowest tests

### ISSUE THREAD

**Issue by tikkss** [test-unit/test-unit#253]
Hi, I'm a contributor of [Improve speed for test · Issue #188 · red-data-tools/red-datasets](https://github.com/red-data-tools/red-datasets/issues/188).

I want to find the slowest tests to improve test execution time. But there are many tests and it takes a long time to identify them.

I would like to propose a new feature for the summary output of test-unit. The idea is to show the N slowest tests in the final summary output.

I considered adding the following command-line options:

```console
        --n-slowest-tests=N          Shows the slowest tests in the summary output
                                     (10)
```

**Comment by kou** [comment]
How about `--[no-]report-slow-tests`?
In general, the slowest is only important. So we may be able to use constant N (5? or something) for this.

**Comment by tikkss** [comment]
Thanks! @kou

Using `--[no-]report-slow-tests` sounds good.

I agree that focusing on the slowest tests is most important. Using a constant value like 5 for the top slow tests is good approach.

How about following command-line options?

```console
        --[no-]report-slow-tests     Shows the top 5 slow tests in the summary output
```

**Comment by kou** [comment]
I like it.

**Comment by tikkss** [comment]
I think steps to implement:

1. Find out how to get the test execution time and the name of the test case (or test suite ?)
2. Find out how to show in the test result summary
3. Implement the option setting (at this step, specifying the option will result in an error)
4. Get the top 5 slow tests
5. Sort the tests in descending order of test execution time
6. Show this information in the test result summary

I plan to implement steps 3-6 incrementally, with each step being sent as a separate pull request.

**Comment by tikkss** [comment]
Here is the current progress.

> 1. Find out how to get the test execution time and the name of the test case (or test suite ?)

I found out how to get the name of the test case:
---

https://github.com/test-unit/test-unit/blob/25c9d39a8dd0d51e8411c4da8eb08769638c9eac/lib/test/unit/ui/console/testrunner.rb#L421

But `test.local_name` is not sufficient because it does not include the class name.
Using `test.name` might be better as it includes the class name.

```rb
test.local_name # => e.g.) test_capture_output
test.name       # => e.g.) test_capture_output(TestUnitOutput)
```

I found out how to get the test execution time:
---

https://github.com/test-unit/test-unit/blob/25c9d39a8dd0d51e8411c4da8eb08769638c9eac/lib/test/unit/ui/console/testrunner.rb#L457

But there are two ways to get the execution time:

1. `(Time.now - @test_start)`
2. `(test.elapsed_time)`

Option 1 might be better because it maintains consistency with the `--verbose` option.


The details are as follows:

To compare both times, I implemented the following:

```diff
diff --git a/lib/test/unit/ui/console/testrunner.rb b/lib/test/unit/ui/console/testrunner.rb
index 4df20a1..ebee597 100644
--- a/lib/test/unit/ui/console/testrunner.rb
+++ b/lib/test/unit/ui/console/testrunner.rb
@@ -418,7 +418,7 @@ module Test
             return unless output?(VERBOSE)

             tab_width = 8
-            name = test.local_name
+            name = "#{test.local_name}(Time.now - @test_start)"
             separator = ":"
             left_used = indent.size + name.size + separator.size
             right_space = tab_width * 2
@@ -455,6 +455,27 @@ module Test
             return unless output?(VERBOSE)

             output(": (%f)" % (Time.now - @test_start), nil, VERBOSE)
+
+            # 2. `(test.elapsed_time)`
+            tab_width = 8
+            name = "#{test.local_name}(test.elapsed_time)"
+            separator = ":"
+            left_used = indent.size + name.size + separator.size
+            right_space = tab_width * 2
+            left_space = @progress_row_max - right_space
+            if (left_used % tab_width).zero?
+              left_space -= left_used
+              n_tabs = 0
+            else
+              left_space -= ((left_used / tab_width) + 1) * tab_width
+              n_tabs = 1
+            end
+            n_tabs += [left_space, 0].max / tab_width
+            tab_stop = "\t" * n_tabs
+            output_single("#{indent}#{name}#{separator}#{tab_stop}",
+                          nil,
+                          VERBOSE)
+            output_progress(".", color("pass-marker"))
+            output(": (%f)" % (test.elapsed_time), nil, VERBOSE)
           end

           def suite_name(prefix, suite)
```

After running the following command:

```console
$ ruby -I lib test/run-test.rb -v -t TestUnitOutput --progress-row-max=72
Loaded suite test
Started
util:
  TestUnitOutput:
    test_capture_output(Time.now - @test_start):        .: (0.000293)
    test_capture_output(test.elapsed_time):             .: (0.000251)

Finished in 0.00078 seconds.
------------------------------------------------------------------------
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------------------------------------------------------------------------
1282.05 tests/s, 1282.05 assertions/s
```

1 is longer than 2 (just a little).
1 is used with the `--verbose` option.

**Comment by tikkss** [comment]
## 2. Find out how to show in the test result summary

I found it:

https://github.com/test-unit/test-unit/blob/25c9d39a8dd0d51e8411c4da8eb08769638c9eac/lib/test/unit/ui/console/testrunner.rb#L391

I think the test result summary should includes below:

* Test source location (easy to jump in editor)
* Test name
* Execution time

Output summary example in [red-datasets](https://github.com/red-data-tools/red-datasets):

```console
$ ruby test/run-test.rb --report-slow-tests --progress-row-max=72
Loaded suite test
Started
Finished in 67.022027 seconds.
------------------------------------------------------------------------
199 tests, 240 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------------------------------------------------------------------------
2.97 tests/s, 3.58 assertions/s
------------------------------------------------------------------------
Top 5 slow tests
test: #each(GeoloniaTest):                                     10.025415
/Users/zzz/src/github.com/red-data-tools/red-datasets/test/test-geolonia.rb:6
test: #each(DiamondsTest):                                      5.373408
/Users/zzz/src/github.com/red-data-tools/red-datasets/test/test-diamonds.rb:10
test: #each(HouseOfRepresentativeTest):                         3.847304
/Users/zzz/src/github.com/red-data-tools/red-datasets/test/test-house-of-representative.rb:10
test: #each(AdultTest::train):                                  3.762340
/Users/zzz/src/github.com/red-data-tools/red-datasets/test/test-adult.rb:11
test: #to_table(FashionMNISTTest::Normal::train):               3.485701
/Users/zzz/src/github.com/red-data-tools/red-datasets/test/test-fashion-mnist.rb:42
```

**Comment by kou** [comment]
Could you show it before statistics?

```console
$ ruby test/run-test.rb --report-slow-tests --progress-row-max=72
Loaded suite test
Started
Finished in 67.022027 seconds.
------------------------------------------------------------------------
Top 5 slow tests
test: #each(GeoloniaTest):                                     10.025415
/Users/zzz/src/github.com/red-data-tools/red-datasets/test/test-geolonia.rb:6
test: #each(DiamondsTest):                                      5.373408
/Users/zzz/src/github.com/red-data-tools/red-datasets/test/test-diamonds.rb:10
test: #each(HouseOfRepresentativeTest):                         3.847304
/Users/zzz/src/github.com/red-data-tools/red-datasets/test/test-house-of-representative.rb:10
test: #each(AdultTest::train):                                  3.762340
/Users/zzz/src/github.com/red-data-tools/red-datasets/test/test-adult.rb:11
test: #to_table(FashionMNISTTest::Normal::train):               3.485701
/Users/zzz/src/github.com/red-data-tools/red-datasets/test/test-fashion-mnist.rb:42
------------------------------------------------------------------------
199 tests, 240 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------------------------------------------------------------------------
2.97 tests/s, 3.58 assertions/s
------------------------------------------------------------------------
```

We may want to show command lines to re-run the slow test easily:

```console
$ ruby test/run-test.rb --report-slow-tests --progress-row-max=72
Loaded suite test
Started
Finished in 67.022027 seconds.
------------------------------------------------------------------------
Top 5 slow tests
test: #each(GeoloniaTest):                                     10.025415
/Users/zzz/src/github.com/red-data-tools/red-datasets/test/test-geolonia.rb:6
ruby test/run-test.rb --report-slow-tests --progress-row-max=72 --location=/Users/zzz/src/github.com/red-data-tools/red-datasets/test/test-geolonia.rb:6
...
```

**Comment by tikkss** [comment]
Thanks for your comment.

> Could you show it before statistics?

OK!

> We may want to show command lines to re-run the slow test easily:

Sounds nice!

I would like to implement 3-6 steps incrementally!

**Comment by tikkss** [comment]
> We may want to show command lines to re-run the slow test easily:

@kou Could you please help me if you know?

### In summary

* How to get switches?
* Is it okay if we use `OptionParser#order` instead of `OptionParser#order!`

### In Detail

I examined how to get command line metadata in ruby program.

What is command line metadata? I confirmed the following command line:

```console
$ ruby --help | head -n1
Usage: ruby [switches] [--] [programfile] [arguments]
```

Metadata are:

1. switches
2. programfile
3. arguments

1 is cannot get in ruby program
2 is `$0`
3 is `$*` but get blank array in following:

https://github.com/test-unit/test-unit/blob/35ac7978fa89bf7c45012837fd79345f93e94943/lib/test/unit/ui/console/testrunner.rb#L401-L404

```ruby
              @test_statistics.sort_by {|statistic| -statistic[:elapsed_time]}
                              .first(N_REPORT_SLOW_TESTS)
                              .each do |slow_statistic|
                pp ["$*:", $*] # => []
              end
```

Because `ARGV` changes destructively:

https://github.com/test-unit/test-unit/blob/24fb08fe31835b0d9ade80fb2f51554e55d1a74a/lib/test/unit/autorunner.rb#L192

If changes non-destructively, 3 is can be getted.

```diff
-          options.order!(args) {|arg| add_test_path(arg)}
+          options.order(args) {|arg| add_test_path(arg)}
```

Is it okay if we make this change non-destructively?

**Comment by tikkss** [comment]
Thanks for your suggestion. Sounds nice! I'll try it.

By the way, assuming `ruby -I lib test/run_test.rb --report-slow-tests`, how to get `-I lib` in ruby program? I didn't found that in https://rurema.clear-code.com/3.3/class/Kernel.html

**Comment by kou** [comment]
We may be able to generate it from `$LOAD_PATH`.

**Comment by tikkss** [comment]
I was too focused on finding a way to get the switches. I'll try it. Thanks!
