### ISSUE TITLE
Pow could not start application after update.

### ISSUE THREAD

**Issue by vicovictor** [test-unit/test-unit#32]
Here's the error message when I tried to start my Rails app with Pow.

`Error starting application
Your Rack app raised an exception when Pow tried to run it.
ArgumentError: wrong number of arguments (1 for 0)
~/.rvm/gems/ruby-1.9.3-p194/gems/test-unit-2.5.0/lib/test-unit.rb:10:in `run'
~/Sites/qhuen/config.ru:4:in `block in <main>'
~/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/builder.rb:4:in `instance_eval'
~/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/builder.rb:4:in `initialize'
~/Sites/qhuen/config.ru:1:in `new'
~/Sites/qhuen/config.ru:1:in `<main>' ~/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:50:in `eval' ~/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:50:in `load_config' ~/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:43:in `initialize' ~/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:13:in `new' ~/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:13:in `run' ~/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/bin/nack_worker:4:in `<main>'`

Using test-unit (2.5.0). When I removed test-unit from my Gemfile, and ran `bundle install`, Pow could start ok.

**Comment by yevgenko** [comment]
Unfortunately the following broke the application to run on Heroku:

    gem "test-unit", :require => "test/unit"

**Comment by yevgenko** [comment]
Going to change 'run' to 'self.run' in config.ru as suggested in https://github.com/basecamp/pow/issues/303

**Comment by kou** [comment]
Use the following:

```ruby
gem "test-unit", :require => false
```

**Comment by kou** [comment]
Or try test-unit 3.1.5.

**Comment by yevgenko** [comment]
@kou, it helped

Thank you a lot!
