### ISSUE TITLE
$SAFE level 3 doesn't work in conjunction with test-unit

### ISSUE THREAD

**Issue by bakis2011** [test-unit/test-unit#91]
I get a SecurityError due to this line in assertions.rb:1716:
```ruby
size = ENV["TEST_UNIT_MAX_DIFF_TARGET_STRING_SIZE"]
```

Is there any way to run test-unit in SAFE level 3?

**Comment by kou** [comment]
Could you show code that reproduces the problem?

And why do you want to run test-unit in SAFE level 3?

**Comment by bakis2011** [comment]
There's some really simple code showing it. It's actually a different error, but it's still a security error.

```ruby
require 'test/unit'
$SAFE = 3

class TestSomething < Test::Unit::TestCase
  def test_assert
    assert_equal 1, 1
  end
end
```

I need to run in SAFE level 3, because i'm "eval"ing ruby code that users input in a web form, so I need to ensure they're not able to do anything that could compromise the system.

I think I've found a solution that uses MiniTest, but that's neither here nor there.

**Comment by kou** [comment]
Use `Thread` to affect `$SAFE` scope:

```ruby
require 'test/unit'

class TestSomething < Test::Unit::TestCase
  def test_assert
    p [:outer, :before, $SAFE]
    Thread.new do
      $SAFE = 3
      p [:inner, $SAFE]
      assert_equal 1, 1
    end.join
    p [:outer, :after, $SAFE]
  end
end
```

```text
% ruby /tmp/b.rb
Loaded suite /tmp/b
Started
[:outer, :before, 0]
[:inner, 3]
[:outer, :after, 0]
.

Finished in 0.000998511 seconds.
--------------------------------------------------------------------------------
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------
1001.49 tests/s, 1001.49 assertions/s
```

FYI: SAFE level 3 isn't safe for evaluating users input. Try the following code:

```ruby
$SAFE = 3

p :before
exit!
p :after
```
