### ISSUE TITLE
Failure when using --priority-mode

### ISSUE THREAD

**Issue by djberg96** [test-unit/test-unit#95]
Hi,

ruby 2.1.3p242 (2014-09-19 revision 47630) [x64-mingw32]
Windows 7
test-unit 3.0.9

I'm having trouble running with the --priority-mode switch. Here's a simple test file:

    require 'test-unit'

    class Test_Foo < Test::Unit::TestCase
      def setup
        @x = 5
      end

      test "test alpha" do
        assert_equal(5, @x)
      end

      test "test beta" do
        assert_equal(6, @x)
      end

      test "test gamma" do
        assert_equal(7, @x)
      end

      def teardown
        @x = nil
      end
    end

Here were the results:

    C:\Users\djberge\Programming\Ruby\Test>ruby test_foo.rb --priority-mode low
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': Not a directory @ dir_s_mkdir -    C:/Users/djberge/Programming/Ruby/Test/.test-result/Test_Foo/test: test alpha (Errno::ENOTDIR)
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:208:in `each'
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/priority.rb:135:in `block in result_dir'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/priority.rb:132:in `each'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/priority.rb:132:in `result_dir'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/priority.rb:145:in `passed_file'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/priority.rb:121:in `previous_test_success?'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/priority.rb:116:in `need_to_run?'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:289:in `block (2 levels) in options'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:45:in `[]'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:45:in `block in include?'

        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:44:in `each'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:44:in `include?'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:19:in `block in add_suite'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:18:in `each'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:18:in `find_all'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:18:in `add_suite'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:65:in `block in add_test_case'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:62:in `each'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:62:in `add_test_case'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:38:in `block in add_test_cases'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:37:in `each'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector.rb:37:in `add_test_cases'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/collector/descendant.rb:13:in `collect '
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:84:in `block in <class:AutoRunner>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:394:in `[]'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:394:in `run'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:59:in `run'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/test-unit-3.0.9/lib/test/unit.rb:502:in `block (2 levels) in <top (required)>'

**Comment by kou** [comment]
Windows...

Could you try the following script?

```ruby
require "fileutils"

FileUtils.mkdir_p(".test-result/Test_Foo/test test alpha")
FileUtils.mkdir_p(".test-result/Test_Foo/test: test alpha")
```

Both of them can be created?

**Comment by djberg96** [comment]
This code fails:
  
    FileUtils.mkdir_p(".test-result/Test_Foo/test: test alpha")

    Errno::ENOTDIR: Not a directory @ dir_s_mkdir - .test-result/Test_Foo/test: test alpha
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir'
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:208:in `each'
        from C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
        from (irb):3
        from C:/Ruby21-x64/bin/irb:11:in `<main>'

Windows doesn't allow colons in filenames.

https://msdn.microsoft.com/en-us/library/aa365247(VS.85)

**Comment by kou** [comment]
Thanks for trying it!
I've fixed it at mater.

**Comment by djberg96** [comment]
Thanks! There may be other bits that need updating. Or perhaps just the tests need modification:

    C:/Ruby21-x64/bin/ruby.exe test/run-test.rb
    Loaded suite test
    Started
    ........................................................................................................................

    .................................................................................................O
    ========================================================================================================================

    test for JRuby [test_error_inside_jruby(TestCodeSnippet::TestJRuby)]
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/omission.rb:86:in `omit'
    ========================================================================================================================

    ...........................................................................................................E
    ========================================================================================================================

    Error: test_colon_and_space(TestUnitPriority::TestFileName): Errno::EINVAL: Invalid argument @ dir_s_mkdir - C:/Users/dj
    berge/Repositories/test-unit/test/.test-result/TestUnitPriority::TestFileName::SpecialNameTestCase
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:135:in `block in result_dir'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:132:in `each'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:132:in `result_dir'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:145:in `passed_file'
    C:/Users/djberge/Repositories/test-unit/test/test-priority.rb:144:in `assert_escaped_name'
    C:/Users/djberge/Repositories/test-unit/test/test-priority.rb:139:in `test_colon_and_space'
         136:     end
         137:
         138:     def test_colon_and_space
      => 139:       assert_escaped_name("test_colon__have_space", "test: have space")
         140:     end
         141:
         142:     def assert_escaped_name(expected, test_method_name)
    ========================================================================================================================

    E
    ========================================================================================================================

    Error: test_equal(TestUnitPriority::TestFileName): Errno::EINVAL: Invalid argument @ dir_s_mkdir - C:/Users/djberge/Repo
    sitories/test-unit/test/.test-result/TestUnitPriority::TestFileName::SpecialNameTestCase
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:135:in `block in result_dir'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:132:in `each'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:132:in `result_dir'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:145:in `passed_file'
    C:/Users/djberge/Repositories/test-unit/test/test-priority.rb:144:in `assert_escaped_name'
    C:/Users/djberge/Repositories/test-unit/test/test-priority.rb:135:in `test_equal'
         132:     end
         133:
         134:     def test_equal
      => 135:       assert_escaped_name("test_equal.equal", "test_equal=")
         136:     end
         137:
         138:     def test_colon_and_space
    ========================================================================================================================

    E
    ========================================================================================================================

    Error: test_exclamation(TestUnitPriority::TestFileName): Errno::EINVAL: Invalid argument @ dir_s_mkdir - C:/Users/djberg
    e/Repositories/test-unit/test/.test-result/TestUnitPriority::TestFileName::SpecialNameTestCase
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:135:in `block in result_dir'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:132:in `each'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:132:in `result_dir'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:145:in `passed_file'
    C:/Users/djberge/Repositories/test-unit/test/test-priority.rb:144:in `assert_escaped_name'
    C:/Users/djberge/Repositories/test-unit/test/test-priority.rb:131:in `test_exclamation'
         128:     end
         129:
         130:     def test_exclamation
      => 131:       assert_escaped_name("test_exclamation.destructive", "test_exclamation!")
         132:     end
         133:
         134:     def test_equal
    ========================================================================================================================

    E
    ========================================================================================================================

    Error: test_question(TestUnitPriority::TestFileName): Errno::EINVAL: Invalid argument @ dir_s_mkdir - C:/Users/djberge/R
    epositories/test-unit/test/.test-result/TestUnitPriority::TestFileName::SpecialNameTestCase
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    C:/Ruby21-x64/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:135:in `block in result_dir'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:132:in `each'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:132:in `result_dir'
    C:/Users/djberge/Repositories/test-unit/lib/test/unit/priority.rb:145:in `passed_file'
    C:/Users/djberge/Repositories/test-unit/test/test-priority.rb:144:in `assert_escaped_name'
    C:/Users/djberge/Repositories/test-unit/test/test-priority.rb:127:in `test_question'
         124:     end
         125:
         126:     def test_question
      => 127:       assert_escaped_name("test_question.predicate", "test_question?")
         128:     end
         129:
         130:     def test_exclamation
    ========================================================================================================================

    ......................................

    Finished in 1.029602 seconds.
    ------------------------------------------------------------------------------------------------------------------------

    367 tests, 1397 assertions, 0 failures, 4 errors, 0 pendings, 1 omissions, 0 notifications
    98.9071% passed
    ------------------------------------------------------------------------------------------------------------------------

    356.45 tests/s, 1356.83 assertions/s
    rake aborted!
    Command failed with status (1): [C:/Ruby21-x64/bin/ruby.exe test/run-test.r...]
    C:/Users/djberge/Repositories/test-unit/Rakefile:70:in `block in <top (required)>'
    Tasks: TOP => test
    (See full trace by running task with --trace)

**Comment by kou** [comment]
Oh...
I also supported it!

And I started to use AppVeyor for testing on Windows: https://ci.appveyor.com/project/kou/test-unit

**Comment by djberg96** [comment]
Thank you! I did not know about AppVeyor. I may have to start using that.
