### ISSUE TITLE
Unable to use tk runner

### ISSUE THREAD

**Issue by djberg96** [test-unit/test-unit#97]
Hi,

ruby 2.2.1
test-unit 3.0.9

I have tk installed, and installed test-unit-full. I was just experimenting with the tk runner, but I can't seem to make it work:

> ruby -Ilib -r tk test/test_getopt_std.rb
> /usr/local/lib/ruby/gems/2.2.0/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:410:in `load_config': undefined method`[]' for false:FalseClass (NoMethodError)
>     from /usr/local/lib/ruby/gems/2.2.0/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:452:in `load_global_config'
>     from /usr/local/lib/ruby/gems/2.2.0/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:145:in`initialize'
>     from /usr/local/lib/ruby/gems/2.2.0/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:55:in `new'
>     from /usr/local/lib/ruby/gems/2.2.0/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:55:in`run'
>     from /usr/local/lib/ruby/gems/2.2.0/gems/test-unit-3.0.9/lib/test/unit.rb:502:in `block (2 levels) in <top (required)>'

**Comment by djberg96** [comment]
Ok, I think this happened because I had a .test-unit.yml file but no runner specified. Still, once I deleted that file and ran with the tk runner, it seemed to default to a console output.

**Comment by kou** [comment]
Could you show your .test-unit.yml?

**Comment by djberg96** [comment]
I deleted it. It should work with the -r switch, though, right?

**Comment by kou** [comment]
Right.

**Comment by djberg96** [comment]
Are you able to use the Tk runner with the -r switch, or are you seeing the same thing I am?

**Comment by kou** [comment]
The Tk runner doesn't report any error on my environment but it just shows an empty window... It doesn't work...

**Comment by djberg96** [comment]
Any luck?

**Comment by djberg96** [comment]
@kou With ruby 2.4.x and test-unit 3.2.x I see what you're seeing now. It just does nothing now - no errors - and the tests still seem to complete on the console. But, Tk isn't working.

**Comment by kou** [comment]
Do you want to use Tk runner? If you want to use, can you try to make Tk runner workable again?

**Comment by djberg96** [comment]
@kou I'll have to figure out how. Any documentation that you can point me at to get me started?

**Comment by djberg96** [comment]
Pretty much use rspec these days...
